apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: frontend-service
  namespace: default
spec:
  interval: 1m0s
  prune: true
  images:
    - name: nginx
      newName: nginx # {"$imagepolicy": "flux-system:apps/nginx:name"}
      newTag: "1.23" # {"$imagepolicy": "flux-system:apps/nginx:tag"}