---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/part-of: nginx
spec:
  interval: 1h0m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      version: "4.4.2"
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1h0m0s
  values:
    cr:
      create: true
      namespace: ingress-nginx
