apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
    version: "v1"
spec:
  template:
    spec:
      containers:
      - name: frontend-service
        image: nginx:mainline
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ENVIRONMENT
          value: "development"