apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    version: "v1"
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ENVIRONMENT
          value: "development"