apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/podinfo
- policy.yaml
- deploy.yaml
images:
- name: ghcr.io/stefanprodan/podinfo
  newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "default:podinfo:name"}
  newTag: 5.0.3 # {"$imagepolicy": "default:podinfo:tag"}
