---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/istio-gateway
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

