apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend-service
    version: "v1"
spec:
  selector:
    app: frontend-service
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: 80