apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
  labels:
    app: podinfo
    version: "v1"
spec:
  selector:
    app: podinfo
  ports:
    - name: http-80
      port: 8080
      protocol: TCP
      targetPort: 9898