---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: ssh://git@github.com/kumar-ulab/flux-workbook

