apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    version: "v1"
spec:
  selector:
    app: nginx
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: 80